#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

last_refs=$(jq -r '.version.ref // ""' < $payload)

destination=$TMPDIR/redis-resource-check
mkdir -p $destination
cd $destination

all_keys=()
for key_pattern in "${keys[@]}"
do
  while read -r
  do
    all_keys+=($REPLY)
  done < <(eval "redis-cli --raw $connect_opts keys '${key_pattern}'")
done

if [[ "${#all_keys[@]}" -eq 0 ]]
then
  new_ref=0
else
  for key in "${all_keys[@]}"
  do
    value="$(eval "redis-cli --raw $connect_opts get '${key}'")"
    echo -n "$value" > "${key}"
  done
  new_ref="$(calc_reference)"
fi

if [[ "$new_ref" == "$last_refs" ]]
then
  echo "[]" >&3
else
  jq -n "[
    {\"ref\": \"$new_ref\"}
  ]" >&3
fi
